"""Regenerates reports/stats_report.{csv,md} from the sim database views.

    SIM_PGPASSWORD=<local-only> python3 reports/sim_report.py [engine_commit]

The commit defaults to the last one that changed the engine; see sim_schema.sql for the statistics.
"""
import csv, io, os, subprocess, sys
from pathlib import Path

HERE = Path(__file__).parent
# Same key as sim_run.sh: the last commit that changed the engine.
ENGINE = ["flutter_client/lib/game", "flutter_client/lib/logic", "flutter_client/lib/net",
          "flutter_client/lib/telemetry", "packages/mahjong_core/lib"]
COMMIT = sys.argv[1] if len(sys.argv) > 1 else subprocess.check_output(
    ["git", "log", "-1", "--format=%h", "--", *ENGINE], text=True, cwd=HERE.parent).strip()
QUERY = f"select * from sim_report where engine_commit = '{COMMIT}'"
METRICS = {"win_rate": "Win Rate", "deal_in_rate": "Deal-in Rate",
           "points_pct": "Ending Points (% vs start)", "placement": "Ending Placement"}
RULESETS = {"riichi": 0, "hongKong": 1, "taiwanese": 2}
ORDER = {"defensive": 0, "balanced": 1, "aggressive": 2, "speed": 0, "points": 0,
         "placement": 1, None: -1, "": -1}


def num(x, d=3):
    return "" if x in ("", None) else f"{float(x):,.{d}f}"


def main():
    env = {**os.environ, "PGHOST": "127.0.0.1", "PGPORT": "15439",
           "PGUSER": "postgres", "PGDATABASE": "postgres",
           "PGPASSWORD": os.environ["SIM_PGPASSWORD"]}
    out = subprocess.check_output(["psql", "-X", "--csv", "-c", QUERY], env=env, text=True)
    rows = list(csv.DictReader(io.StringIO(out)))
    if not rows:
        sys.exit(f"no results for engine commit {COMMIT}")
    rows.sort(key=lambda r: (RULESETS[r["ruleset"]], int(r["minimum"]),
                             r["game_length"] != "east", r["decision_maker"] != "simple_bot",
                             ORDER[r["style"]], ORDER[r["focus"]], ORDER[r["strategy"]],
                             list(METRICS).index(r["metric"])))
    seeds = {(r["seed_min"], r["seed_max"], r["n"]) for r in rows}
    if len(seeds) != 1:
        sys.exit(f"arms cover different seeds: {sorted(seeds)}")
    lo, hi, n = seeds.pop()
    if int(hi) - int(lo) + 1 != int(n):
        sys.exit(f"seeds {lo}..{hi} are not {n} consecutive seeds")

    cols = ["metric", "variant", "game_length", "seeds", "decision_maker", "style",
            "focus", "strategy", "n", "mean", "sd", "se", "cv", "sd_ucl", "n_pairs",
            "rho", "mean_diff", "p_holm", "delta", "n_unpaired", "n_paired", "n_paired_ucl"]
    with open(HERE / "stats_report.csv", "w", newline="") as f:
        w = csv.writer(f, lineterminator="\n")
        w.writerow(cols)
        for r in rows:
            w.writerow([r["metric_label"], r["variant"], r["game_length_label"],
                        f"{lo}..{hi}", r["decision_maker_label"]] +
                       [r[c].capitalize() for c in ("style", "focus", "strategy")] +
                       [r[c] for c in cols[8:]])

    worst = {}
    for r in rows:
        if r["n_paired_ucl"]:
            k = r["metric_label"]
            worst[k] = max(worst.get(k, (0, 0)), (int(float(r["n_paired_ucl"])),
                                                   int(float(r["n_unpaired"]))))
    md = [
        "# TileSense seat-0 statistics report", "",
        f"Engine commit `{COMMIT}` (the last commit to change the game engine). Seat 0 is the decision maker; seats 1–3 are the shipped "
        f"`SimpleBot`. Every row uses the same **{n} consecutive seeds, {lo}–{hi}**. "
        "Game-by-game results live in the local `tilesense-sim` PostgreSQL database "
        "(`reports/sim_schema.sql`); this file is generated by `reports/sim_report.py`.", "",
        "- **Win Rate** / **Deal-in Rate**: seat-0 wins (or deal-ins) ÷ hands played, per game.",
        "- **Ending Points (% vs start)**: 100 · (end − start) / start, where start is "
        "25,000 (Riichi) or 1,000 chips (Hong Kong, Taiwanese).",
        "- **Ending Placement**: 1–4, ties split (e.g. 2.5).",
        "- **SD**: standard deviation of the per-seed values. **SE** = SD/√n. **CV** = SD/|Mean|. "
        "**SD UCL**: one-sided 80% upper confidence limit of the SD.",
        "- **Guide rows** are compared with the Simple Bot row of the same variant and length "
        "on the same seeds (paired). **ρ**: correlation between the guide's and the bot's "
        "value on each seed. **Δ**: mean of guide − bot. **Holm p**: two-sided, Holm-adjusted "
        "within each variant, length and metric.",
        "- **Seeds needed** to detect an effect δ (two-sided α = 0.05, power 0.80). δ is 10 "
        "percentage points of stack for Ending Points and 10% of the bot's mean otherwise. "
        "*Unpaired* ignores the shared seeds. *Paired* uses the SD of the per-seed "
        "differences. *Paired (UCL)* uses that SD's 80% upper confidence limit, so a CV "
        "estimated from a small sample does not under-power the plan; this is the one to use.",
        "- Hong Kong and Taiwanese pin Style to Balanced and Strategy to Points in the game, "
        "so only Focus varies there.", "",
        "## Seeds needed per comparison (worst case across guide arms)", "",
        "| Metric | Paired (UCL) | Unpaired, same arm |", "|---|--:|--:|",
        *[f"| {k} | {v[0]:,} | {v[1]:,} |" for k, v in worst.items()], "",
        "## All rows", "",
        "| Metric | Variant | Game Length | Decision Maker | Style | Focus | Strategy | Mean | SD "
        "| SE | CV | SD UCL | ρ | Δ | Holm p | δ | Seeds: unpaired | paired | paired (UCL) |",
        "|---|---|---|---|---|---|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|",
    ]
    for r in rows:
        control = r["decision_maker"] == "simple_bot"
        md.append("| " + " | ".join([
            r["metric_label"], r["variant"], r["game_length_label"], r["decision_maker_label"],
            *[(r[c] or "—").capitalize() for c in ("style", "focus", "strategy")],
            num(r["mean"]), num(r["sd"]), num(r["se"]), num(r["cv"]), num(r["sd_ucl"]),
            num(r["rho"]), num(r["mean_diff"]),
            "" if control else f"{float(r['p_holm']):.2g}", num(r["delta"]),
            num(r["n_unpaired"], 0), num(r["n_paired"], 0), num(r["n_paired_ucl"], 0),
        ]) + " |")
    (HERE / "stats_report.md").write_text("\n".join(md) + "\n")
    print(f"{len(rows)} rows, seeds {lo}..{hi}")


if __name__ == "__main__":
    main()
